-- MySQL Script generated by MySQL Workbench
-- Thu Jun  3 16:20:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coffeemintdb-jdevd010
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coffeemintdb-jdevd010
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffeemintdb-jdevd010` DEFAULT CHARACTER SET utf8 ;
USE `coffeemintdb-jdevd010` ;

-- -----------------------------------------------------
-- Table `coffeemintdb-jdevd010`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffeemintdb-jdevd010`.`customers` ;

CREATE TABLE IF NOT EXISTS `coffeemintdb-jdevd010`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(12) NULL DEFAULT NULL,
  `address` VARCHAR(128) NULL DEFAULT NULL,
  `photo` VARCHAR(128) NULL DEFAULT NULL,
  `enabled` TINYINT NULL DEFAULT '1',
  `auth_provider` VARCHAR(45) NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `password_change` DATETIME NULL DEFAULT NULL,
  `veirfied` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coffeemintdb-jdevd010`.`persistent_logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffeemintdb-jdevd010`.`persistent_logins` ;

CREATE TABLE IF NOT EXISTS `coffeemintdb-jdevd010`.`persistent_logins` (
  `username` VARCHAR(64) NOT NULL,
  `series` VARCHAR(64) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `last_used` TIMESTAMP NOT NULL,
  PRIMARY KEY (`series`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coffeemintdb-jdevd010`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffeemintdb-jdevd010`.`roles` ;

CREATE TABLE IF NOT EXISTS `coffeemintdb-jdevd010`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coffeemintdb-jdevd010`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffeemintdb-jdevd010`.`users` ;

CREATE TABLE IF NOT EXISTS `coffeemintdb-jdevd010`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `enabled` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coffeemintdb-jdevd010`.`users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffeemintdb-jdevd010`.`users_roles` ;

CREATE TABLE IF NOT EXISTS `coffeemintdb-jdevd010`.`users_roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `role_fk_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_fk_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `coffeemintdb-jdevd010`.`roles` (`role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_fk_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffeemintdb-jdevd010`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
